routes:
  /essays/:
    controller: channel
    order: published_at desc
    template: drilldown
    filter: tag:[monday_notes, editors_desk, first_drafts, hash-essays, friday_essays, notes]
    data: page.essays
  /editors_desk/:
    controller: channel
    template: drilldown
    filter: primary_tag:editors_desk
    data: tag.editors_desk
  /democracy_essays/:
    controller: channel
    template: democracy_essays
    filter: tag:democracy_essays
    data: tag.democracy_essays
  /q-a/:
    controller: channel
    template: drilldown
    filter: primary_tag:q-a
    data: tag.q-a
  /friday_essays/:
    controller: channel
    template: drilldown
    filter: primary_tag:friday_essays
    data: tag.friday_essays
  /monday_notes/:
    controller: channel
    template: drilldown
    filter: primary_tag:monday_notes
    data: tag.monday_notes
  /notes/:
    controller: channel
    template: drilldown
    filter: primary_tag:notes
    data: tag.notes
  /first_drafts/:
    controller: channel
    template: drilldown
    filter: primary_tag:first_drafts
    data: tag.first_drafts
  /debates/:
    controller: channel
    template: drilldown
    filter: primary_tag:debates
    data: tag.debates
  /podcasts/:
    controller: channel
    template: drilldown
    filter: primary_tag:podcasts
    data: tag.podcasts
  /podcasts/rss-members/:
    template: podcasts-rss
    content_type: text/xml
  /subscribe/:
    template: subscribe
    data: page.subscribe
  /signup/:
    template: signup
    data: page.signup

collections:
  /:
    permalink: /{slug}/
    template: index
    order: published_at desc
    filter: tag:-[friends_enemies, hash-excerpt, hash-onlymail]
  /friends_enemies/:
    permalink: /friends_enemies/{year}/{month}/{day}/{slug}/
    template: friends_enemies
    order: published_at desc
    filter: primary_tag:friends_enemies
    data: tag.friends_enemies

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
